# Generated by Django 5.1.7 on 2025-03-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('unapproved', 'unapproved'), ('pinned', 'pinned')], default='unapproved', max_length=50),
        ),
    ]
