# Generated by Django 5.1.7 on 2025-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_review_is_approved_remove_review_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('unapproved', 'unapproved'), ('banned', 'Banned')], default='unapproved', max_length=50),
        ),
    ]
