# Generated by Django 5.1.7 on 2025-03-23 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('riyadh', 'Riyadh'), ('aseer', 'Aseer'), ('jeddah', 'Jeddah'), ('alula', 'Alula'), ('taif', 'Taif'), ('al-baha', 'Al baha')], max_length=50)),
                ('image', models.URLField(max_length=1000)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2)),
                ('experience_type', models.CharField(choices=[('mental_relaxation', 'راحة نفسية'), ('physical_recovery', 'استشفاء جسدي'), ('physical_activity', 'نشاط بدني')], max_length=50)),
                ('health_condition', models.CharField(choices=[('stress', 'Stress'), ('pain', 'Pain'), ('sleep', 'Sleep'), ('fatigue', 'Fatigue'), ('digestive', 'Digestive'), ('energy', 'Energy')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('mental_relaxation', 'راحة نفسية'), ('physical_recovery', 'استشفاء جسدي'), ('physical_activity', 'نشاط بدني')], max_length=50)),
                ('health_conditions', models.CharField(choices=[('stress', 'Stress'), ('pain', 'Pain'), ('sleep', 'Sleep'), ('fatigue', 'Fatigue'), ('digestive', 'Digestive'), ('energy', 'Energy')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.wellnessplace')),
            ],
        ),
    ]
