# Generated by Django 5.1.7 on 2025-03-27 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=1000)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='base.wellnessplace')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('group', 'جلسة جماعية'), ('private', 'تجربة خاصة'), ('consultation', 'استشارة مع أخصائي')], max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='base.wellnessservice')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
