# Generated by Django 5.1.7 on 2025-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='health_conditions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='avatars/%y/%m/%d'),
        ),
    ]
