# Generated by Django 5.1.7 on 2025-03-28 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_booking_additional_notes_booking_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessplace',
            name='availability',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekends', 'Weekends'), ('weekdays', 'Weekdays')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='wellnessplace',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')], default=90),
        ),
        migrations.AddField(
            model_name='wellnessplace',
            name='group_size',
            field=models.IntegerField(choices=[(1, 'Solo'), (2, '2-4 people'), (5, '5-8 people'), (9, 'More than 8')], default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, default='', help_text='Any additional notes or details provided by the user.', null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the booking was created.', verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='', help_text='The full name of the user making the booking.', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='', help_text='The phone number of the user.', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='The preferred date for the session.', null=True, verbose_name='Preferred Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='The preferred time for the session.', null=True, verbose_name='Preferred Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(help_text='The wellness service being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='base.wellnessservice', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('group', 'جلسة جماعية'), ('private', 'تجربة خاصة'), ('consultation', 'استشارة مع أخصائي')], help_text='Type of session being booked.', max_length=20, verbose_name='Session Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='The user who made the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='description',
            field=models.TextField(help_text='A detailed description of the wellness place.', verbose_name='Place Description'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='experience_type',
            field=models.CharField(choices=[('mental_relaxation', 'راحة نفسية'), ('physical_recovery', 'استشفاء جسدي'), ('physical_activity', 'نشاط بدني')], help_text='The type of experience offered at the wellness place.', max_length=50, verbose_name='Experience Type'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='health_condition',
            field=models.CharField(choices=[('stress', 'Stress'), ('pain', 'Pain'), ('sleep', 'Sleep'), ('fatigue', 'Fatigue'), ('digestive', 'Digestive'), ('energy', 'Energy')], help_text='The health condition supported by the wellness place.', max_length=50, verbose_name='Health Condition'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='image',
            field=models.URLField(help_text='A URL pointing to an image representing the wellness place.', max_length=1000, validators=[django.core.validators.URLValidator()], verbose_name='Place Image URL'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('both', 'English & Arabic')], default='both', help_text='The primary language used at the wellness place.', max_length=4, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='location',
            field=models.CharField(choices=[('riyadh', 'Riyadh'), ('aseer', 'Aseer'), ('jeddah', 'Jeddah'), ('alula', 'Alula'), ('taif', 'Taif'), ('al-baha', 'Al baha')], help_text='The location of the wellness place.', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='name',
            field=models.CharField(help_text='The name of the wellness place.', max_length=255, verbose_name='Place Name'),
        ),
        migrations.AlterField(
            model_name='wellnessservice',
            name='description',
            field=models.TextField(help_text='A detailed description of the wellness service.', verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='wellnessservice',
            name='image',
            field=models.URLField(help_text='A URL pointing to an image representing the service.', max_length=1000, validators=[django.core.validators.URLValidator()], verbose_name='Service Image URL'),
        ),
        migrations.AlterField(
            model_name='wellnessservice',
            name='more_info',
            field=models.TextField(blank=True, help_text='Optional field to store extra details about the service.', null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='wellnessservice',
            name='place',
            field=models.OneToOneField(help_text='The wellness place associated with this service.', on_delete=django.db.models.deletion.CASCADE, related_name='service', to='base.wellnessplace', verbose_name='Wellness Place'),
        ),
        migrations.AlterField(
            model_name='wellnessservice',
            name='title',
            field=models.CharField(help_text='The title of the wellness service.', max_length=255, verbose_name='Service Title'),
        ),
        migrations.CreateModel(
            name='WhatToExpect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('wellness_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='base.wellnessplace')),
            ],
        ),
    ]
