# Generated by Django 5.1.7 on 2025-03-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_wellnessplace_availability_wellnessplace_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessplace',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='wellnessplace',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='wellnessplace',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='wellnessservice',
            name='more_info',
        ),
        migrations.AddField(
            model_name='wellnessservice',
            name='availability',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekends', 'Weekends'), ('weekdays', 'Weekdays')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='wellnessservice',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')], default=90),
        ),
        migrations.AddField(
            model_name='wellnessservice',
            name='group_size',
            field=models.IntegerField(choices=[(1, 'Solo'), (2, '2-4 people'), (5, '5-8 people'), (9, 'More than 8')], default=2),
        ),
        migrations.AddField(
            model_name='wellnessservice',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('both', 'English & Arabic')], default='both', help_text='The primary language used at the wellness service.', max_length=4, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='wellnessplace',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='both', help_text='The primary language used at the wellness place.', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='whattoexpect',
            name='wellness_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='base.wellnessservice'),
        ),
    ]
