# Generated by Django 5.1.7 on 2025-03-28 23:06

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_wellnessplace_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default=base.models.generate_booking_reference, max_length=14, unique=True),
        ),
    ]
