# Generated by Django 5.1.7 on 2025-03-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_booking_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessplace',
            name='content',
            field=models.TextField(default='', help_text='HTML content providing a detailed description of the wellness place.', verbose_name='Place Content'),
        ),
    ]
